### PR TITLE
Reproductible nix build

### PR DESCRIPTION
**Pull request by turboMaCk**
This is WIP nix build. The biggest issue seems to be the graphviz which is being called from path (and thus can collide with system version) instead of being liked. Right now build works but runtime depends on global elm-analuse and graphviz version which is not acceptable. Also minification of js is not implemented

### CODE REVIEW

**Comment by turboMaCk** [comment]
this issue has some relevant info around graphviz dependency https://github.com/NixOS/nixpkgs/issues/4297

**Comment by turboMaCk** [comment]
@jhrcek this is ready

**Comment by jhrcek** [comment]
@turboMaCk Looks great! Would you be willing to get together (call) and walk over how all of this works together?

**Review by jhrcek — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
